=== AAhusk/CS314_Website/server/src/main/resources/TIPTrip.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title" : "TIPTrip schema",
  "description" : "schema for a Trip json file",
  "type"  : "object",
  "properties"  : {
    "requestType" : {
      "type"  : "string"
    },

    "requestVersion"  : {
      "type"  : "integer"
    },

    "options" : {
      "type"  : "object",
      "title" : {
        "type"  : "string"
      },
      "optimization"  : {
        "type"  : "string"
      },
      "earthRadius" : {
        "type"  : "integer",
        "minimum" : 0
      },
      "required"  : ["earthRadius"]
    },

    "places"  : {
      "type"  : "array"
    },

    "distances"  : {
      "type"  : "array"
    }

  },
  "required"  : ["requestType", "requestVersion", "places"]

}

=== AAhusk/CS314_Website/team/documents/TestFiles/TIPTRIP/No_Distances.json
{
    "requestType"    : "trip",
    "requestVersion" : 2,
    "options"        : { "title":"My Trip", 
                         "earthRadius":"3958.8",
                         "optimization":"none" },
    "places"         : [{"name":"Denver",       "latitude": "39.7", "longitude": "-105.0"},
                        {"name":"Boulder",      "latitude": "40.0", "longitude": "-105.4"},
                        {"name":"Fort Collins", "latitude": "40.6", "longitude": "-105.1"}]
  }

=== AAhusk/CS314_Website/client/src/components/Application/Itinerary/14ers.json
{
  "requestType": "trip",
  "requestVersion": 2,
  "options": { "title": "Colorado 14ers", "earthRadius": "3959" },
  "places": [
    { "name": "Mount Elbert", "id": 1, "latitude": "39.1177", "longitude": "-106.4453", "altitude": "14433" },
    { "name": "Mount Massive", "id": 2, "latitude": "39.1875", "longitude": "-106.4756", "altitude": "14421" },
    { "name": "Mount Harvard", "id": 3, "latitude": "38.9243", "longitude": "-106.3208", "altitude": "14420" },
    { "name": "Blanca Peak", "id": 4, "latitude": "37.5774", "longitude": "-105.4857", "altitude": "14345" },
    { "name": "La Plata Peak", "id": 5, "latitude": "39.0294", "longitude": "-106.4729", "altitude": "14336" },
    { "name": "Uncompahgre Peak", "id": 6, "latitude": "38.0716", "longitude": "-107.4621", "altitude": "14309" },
    { "name": "Crestone Peak", "id": 7, "latitude": "37.9667", "longitude": "-105.5853", "altitude": "14294" },
    { "name": "Mount Lincoln", "id": 8, "latitude": "39.3515", "longitude": "-106.1115", "altitude": "14286" },
    { "name": "Grays Peak", "id": 9, "latitude": "39.6337", "longitude": "-105.8175", "altitude": "14270" },
    { "name": "Mount Antero", "id": 10, "latitude": "38.6741", "longitude": "-106.2462", "altitude": "14269" },
    { "name": "Torreys Peak", "id": 11, "latitude": "39.64267", "longitude": "-105.82108", "altitude": "14267" },
    { "name": "Castle Peak", "id": 12, "latitude": "39.0095", "longitude": "-106.86139", "altitude": "14265" },
    { "name": "Quandary Peak", "id": 13, "latitude": "39.3972", "longitude": "-106.1064", "altitude": "14265" },
    { "name": "Mount Evans", "id": 14, "latitude": "39.58821", "longitude": "-105.64359", "altitude": "14264" },
    { "name": "Longs Peak", "id": 15, "latitude": "40.2548", "longitude": "-105.6161", "altitude": "14255" },
    { "name": "Mount Wilson", "id": 16, "latitude": "37.8391", "longitude": "-107.9915", "altitude": "14246" },
    { "name": "Mount Shavano", "id": 17, "latitude": "38.6193", "longitude": "-106.2393", "altitude": "14229" },
    { "name": "Mount Belford", "id": 18, "latitude": "38.9606", "longitude": "-106.3608", "altitude": "14197" },
    { "name": "Crestone Needle", "id": 19, "latitude": "37.96468", "longitude": "-105.57667", "altitude": "14197" },
    { "name": "Mount Princeton", "id": 20, "latitude": "38.7492", "longitude": "-106.2424", "altitude": "14197" },
    { "name": "Mount Yale", "id": 21, "latitude": "38.8442", "longitude": "-106.3137", "altitude": "14196" },
    { "name": "Mount Bross", "id": 22, "latitude": "39.33452", "longitude": "-106.1077", "altitude": "14172" },
    { "name": "Kit Carson Peak", "id": 23, "latitude": "37.97958", "longitude": "-105.6025", "altitude": "14165" },
    { "name": "Maroon Peak", "id": 24, "latitude": "39.0708", "longitude": "-106.989", "altitude": "14156" },
    { "name": "Tabeguache Peak", "id": 25, "latitude": "38.62544", "longitude": "-106.25081", "altitude": "14155" },
    { "name": "Mount Oxford", "id": 26, "latitude": "38.96481", "longitude": "-106.33879", "altitude": "14153" },
    { "name": "Mount Sneffels", "id": 27, "latitude": "38.0036", "longitude": "-107.7922", "altitude": "14150" },
    { "name": "Mount Democrat", "id": 28, "latitude": "39.33956", "longitude": "-106.13989", "altitude": "14148" },
    { "name": "Capitol Peak", "id": 29, "latitude": "39.1502", "longitude": "-107.083", "altitude": "14130" },
    { "name": "Pikes Peak", "id": 30, "latitude": "38.8405", "longitude": "-105.0446", "altitude": "14110" },
    { "name": "Snowmass Mountain", "id": 31, "latitude": "39.1187", "longitude": "-107.0665", "altitude": "14092" },
    { "name": "Mount Eolus", "id": 32, "latitude": "37.6219", "longitude": "-107.6226", "altitude": "14083" },
    { "name": "Windom Peak", "id": 33, "latitude": "37.6212", "longitude": "-107.5919", "altitude": "14082" },
    { "name": "Challenger Point", "id": 34, "latitude": "37.98024", "longitude": "-105.60643", "altitude": "14081" },
    { "name": "Mount Columbia", "id": 35, "latitude": "38.9034", "longitude": "-106.2974", "altitude": "14073" },
    { "name": "Missouri Mountain", "id": 36, "latitude": "38.94755", "longitude": "-106.37836", "altitude": "14067" },
    { "name": "Humboldt Peak", "id": 37, "latitude": "37.9761", "longitude": "-105.555", "altitude": "14064" },
    { "name": "Mount Bierstadt", "id": 38, "latitude": "39.58252", "longitude": "-105.66862", "altitude": "14060" },
    { "name": "Sunlight Peak", "id": 39, "latitude": "37.6273", "longitude": "-107.59579", "altitude": "14059" },
    { "name": "Handies Peak", "id": 40, "latitude": "37.9129", "longitude": "-107.5043", "altitude": "14048" },
    { "name": "Culebra Peak", "id": 41, "latitude": "37.1222", "longitude": "-105.1857", "altitude": "14047" },
    { "name": "Ellingwood Point", "id": 42, "latitude": "37.58251", "longitude": "-105.4925", "altitude": "14042" },
    { "name": "Mount Lindsey", "id": 43, "latitude": "37.5838", "longitude": "-105.4448", "altitude": "14042" },
    { "name": "Little Bear Peak", "id": 44, "latitude": "37.56668", "longitude": "-105.49723", "altitude": "14037" },
    { "name": "Mount Sherman", "id": 45, "latitude": "39.2249", "longitude": "-106.1698", "altitude": "14036" },
    { "name": "Redcloud Peak", "id": 46, "latitude": "37.9409", "longitude": "-107.4217", "altitude": "14034" },
    { "name": "Pyramid Peak", "id": 47, "latitude": "39.0715", "longitude": "-106.9501", "altitude": "14018" },
    { "name": "Wilson Peak", "id": 48, "latitude": "37.8603", "longitude": "-107.9847", "altitude": "14017" },
    { "name": "Wetterhorn Peak", "id": 49, "latitude": "38.0606", "longitude": "-107.5108", "altitude": "14015" },
    { "name": "San Luis Peak", "id": 50, "latitude": "37.9868", "longitude": "-106.9311", "altitude": "14014" },
    { "name": "Mount of the Holy Cross", "id": 51, "latitude": "39.4668", "longitude": "-106.4816", "altitude": "14005" },
    { "name": "Huron Peak", "id": 52, "latitude": "38.9455", "longitude": "-106.438", "altitude": "14003" },
    { "name": "Sunshine Peak", "id": 53, "latitude": "37.92268", "longitude": "-107.42548", "altitude": "14001" }
  ]
}

=== AAhusk/CS314_Website/client/src/components/Application/Itinerary/ski.json
{
  "requestType": "trip",
  "requestVersion": 2,
  "options": { "earthRadius": "6371", "title": "Ski" },
  "places": [
    { "latitude": "N 37° 16'", "longitude": "W 106° 28'", "name": "Wolf Creek" },
    { "latitude": "N 37° 33'", "longitude": "W 107° 30'", "name": "Telluride" },
    { "latitude": "N 38° 18'", "longitude": "W 106° 11'", "name": "Monarch" },
    { "latitude": "N 37° 31'", "longitude": "W 107° 24'", "name": "Silverton" },
    { "latitude": "N 37° 22'", "longitude": "W 107° 29'", "name": "Purgatory" },
    { "latitude": "N 38° 32'", "longitude": "W 106° 34'", "name": "Crested Butte" },
    { "latitude": "N 39° 02'", "longitude": "W 108° 05'", "name": "Powderhorn" },
    { "latitude": "N 39° 06'", "longitude": "W 106° 29'", "name": "Aspen mountain" },
    { "latitude": "N 39° 12'", "longitude": "W 106° 10'", "name": "Ski Cooper" },
    { "latitude": "N 39° 23'", "longitude": "W 106° 13'", "name": "Vail" },
    { "latitude": "N 39° 17'", "longitude": "W 106° 01'", "name": "Breckenridge" },
    { "latitude": "N 39° 24'", "longitude": "W 105° 18'", "name": "Echo Mountain" },
    { "latitude": "N 40° 16'", "longitude": "W 106° 28'", "name": "Steamboat" },
    { "latitude": "N 40° 10'", "longitude": "W 105° 19'", "name": "Estes Valley" },
    { "latitude": "N 39° 33'", "longitude": "W 105° 20'", "name": "Eldora Mountain" },
    { "latitude": "N 39° 31'", "longitude": "W 105° 27'", "name": "Winter Park" }
  ],
  "distances":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
}
